### ISSUE TITLE
[BUG] Shows blank screen after entering repo details

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/bacman#10]
- [ ] I have looked at [the documentation for the app](https://www.ituob.org/docs/), and I still believe there is an issue.

**Describe the issue**

App gives a blank screen after entering details into the initial repo settings screen.

**When does it happen?**

1. Open Bacman
2. Fill in the repo URL, GitHub username, display name and email 
3. Click on the button in the bottom right corner to go to the next screen
4. See blank window

**Expected behavior**

Instead of the blank window, it should display the Bacman interface.

**Screenshots**

<img width="912" alt="Screenshot 2020-05-05 at 9 41 12 PM" src="https://user-images.githubusercontent.com/2649467/81072768-3b4bd000-8f19-11ea-920d-7265490a115b.png">

**Environment**
 - OS: macOS 10.14.6
 - bacman version: 0.2.0

**Additional context**

Suspecting that the issue was due to incompatible settings from previous versions, I did `rm -rf ~/Library/Application Support/bacman`, which allowed me to get to the initial settings screen.
But after the steps above, the same symptom appears.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau did you create a fork of the bacman data repo?

**Comment by ribose-jeffreylau** [comment]
Yes, my fork is here: https://github.com/ribose-jeffreylau/bacman-sample-data
I entered this into the settings.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau if you have 2FA enabled, you need to enter your GitHub's personal access token as password. Can you try?

**Comment by ribose-jeffreylau** [comment]
That's what I did.

**Comment by ribose-jeffreylau** [comment]
Nevermind, I had to `rm -rf ~/Library/Application\ Support/bacman` a second time.  Now it works...

Thanks!
